api_server:
  host: 0.0.0.0
  port: 8081
rw_db:
  user: postgres
  password: ^QHh-ty,fy#"M,gE
  host: 127.0.0.1
  port: 8002
  database: rusix
  max_connections: 10
redis:
  password: c6bfb872-49f6-48bc-858d-2aca0c020702
  host: 127.0.0.1
  port: 8003
  database: 0